### ISSUE TITLE
404 Client Error

### ISSUE THREAD

**Issue by PTarakanov** [scaleway/netbox-netprod-importer#43]
Hello!
I just started using Netbox and Netprod importer, so, maybe I'm doing something wrong, but when I try 

netbox-netprod-importer import -u admin -p -f devices.yml

then I get

`ERROR: netbox_importer: Error when polling device SWITCHNAME: 404 Client Error: Not Found for url: https://netbox-01/api/dcim/_choices/?limit=50 -- `
and HTML body below.

Files:
```
root@lab-dc1-netbox-01:~/.config/netbox-netprod-importer# cat devices.yml 
SWITCHNAME:
    driver: "ios"
    discovery_protocol: "cdp"
    target: "10.x.x.21"
```

```
root@lab-dc1-netbox-01:~/.config/netbox-netprod-importer# cat config.yml 
########################
#### Global options ####
########################

## Be more verbose ##
verbose: None

## Disable ssl warnings in urllib3 ##
disable_ssl_warnings: True


################
#### Netbox ####
################

netbox:
  # Netbox API URL
  url: "https://netbox-01/api"
  # username: "admin"
  # password: "nonono"
  # or to use a token instead
  token: "4acbf1108516c0bcdfe136cf3a07a6c5835160db"


##########################
#### Interconnections ####
##########################

# On some devices, LLDP will expose the host FQDN. If devices are stored on
# Netbox only by their hostname, the interconnection process will not be able
# to find them. Fill this list to strip the domain name from exposed names.
remove_domains:
  - "domain.com"

# vim: set ts=2 sw=2:
```
