### ISSUE TITLE
SSL ignore not working.

### ISSUE THREAD

**Issue by GangstaPirates** [scaleway/netbox-netprod-importer#49]
Hey,
Despite having disable_ssl_warnings set as True or False in the config I still get the following issue when trying to connect to netbox api.

ERROR: netbox_importer: Error when polling device HCC-S009-RT01: HTTPSConnectionPool(host='netboxtest.###.##', port=443): Max retries exceeded with url: /api/dcim/devices/?name=HCC-S009-RT01&limit=50 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)'),))

**Comment by danjaf** [comment]
Same Issue, _disable_ssl_warning_s set to _True_ is not being respected at import:

**Version:** 0.3.3
**Python**: 3.8.5
**certifi**: 2019.11.28
**urllib3**: 1.25.8

~/.config/netbox-netprod-importer/config.yml

```
netbox@netbox:/opt/netbox-netprod-importer$ cat ~/.config/netbox-netprod-importer/config.yml_bak 
#### Global options ####
########################

## Be more verbose ##
verbose: None

## Disable ssl warnings in urllib3 ##
disable_ssl_warnings: True


################
#### Netbox ####
################

netbox:
  # Netbox API URL
  url: "https://172.16.1.114/api"
  # username: "user"
  # password: "password"
  # or to use a token instead
  token: "********************"


##########################
#### Interconnections ####
##########################

# On some devices, LLDP will expose the host FQDN. If devices are stored on
# Netbox only by their hostname, the interconnection process will not be able
# to find them. Fill this list to strip the domain name from exposed names.
remove_domains:
  - "foo.tld"
  - "bar.tld"

# vim: set ts=2 sw=2:
```

command run:

`netbox-netprod-importer import -f devices.yaml`


Error:

`ERROR: netbox_importer: Error when polling device XXXXX-INFRA-NUTSW1: HTTPSConnectionPool(host='172.16.1.114', port=443): Max retries exceeded with url: /api/dcim/devices/?name=XXXXX-INFRA-NUTSW1&limit=50 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))`
